import mongoose from 'mongoose';

const ticketSchema = new mongoose.Schema({
  ticketId: { type: Number, required: true, unique: true },
  guildId: { type: String, required: true },
  channelId: { type: String, default: '' },
  creatorId: { type: String, required: true },
  creatorTag: { type: String, default: '' },
  departmentId: { type: String, default: '' },
  status: { type: String, enum: ['creating', 'open', 'closing', 'closed', 'deleted'], default: 'creating' },
  answers: [{
    questionId: String,
    question: String,
    answer: String,
  }],
  participants: [String],
  reportedUserId: { type: String, default: '' },
  notes: { type: String, default: '' },
  claimedBy: { type: String, default: '' },
  claimedAt: Date,
  locked: { type: Boolean, default: false },
  lockedBy: { type: String, default: '' },
  lockedAt: Date,
  closedAt: Date,
  closedBy: { type: String, default: '' },
  closedById: { type: String, default: '' },
  closeReason: { type: String, default: '' },
  deletedAt: Date,
  deletedBy: { type: String, default: '' },
  firstStaffResponseAt: Date,
  firstStaffResponderId: { type: String, default: '' },
  staffMessageCount: { type: Number, default: 0 },
  userMessageCount: { type: Number, default: 0 },
  lastAlertAt: Date,
  alertCount: { type: Number, default: 0 },
  lastUserMessageAt: Date,
  autoCloseWarned: { type: Boolean, default: false },
  closeRequest: {
    active: { type: Boolean, default: false },
    requestedBy: { type: String, default: '' },
    requestedAt: Date,
    reason: { type: String, default: '' },
  },
  transcript: {
    generated: { type: Boolean, default: false },
    filename: { type: String, default: '' },
    generatedAt: Date,
    generatedBy: { type: String, default: '' },
    logMessageId: { type: String, default: '' },
    dmDelivered: { type: Boolean, default: false },
  },
  history: [{
    action: String,
    performedBy: String,
    targetId: String,
    oldValue: String,
    newValue: String,
    reason: String,
    timestamp: Date,
  }],
}, { timestamps: true });

export default mongoose.models.Ticket || mongoose.model('Ticket', ticketSchema);
