export const ticketConfig = {
  logChannelId: process.env.TICKET_LOG_CHANNEL_ID || '1530531646397481103',
  transcriptChannelId: '1530583332730048562',
  errorLogChannelId: '1530531650675413074',

  ticketLimitPerDepartment: 2,
  alertCooldownSeconds: 1800,
  deletionDelayMs: 5000,
  transcriptDM: true,
  autoCloseInactiveHours: 48,
  autoCloseWarnHours: 6,

  channelNaming: {
    format: '{prefix}-{ticketId}',
    prefixes: {
      general: 'general',
      reports: 'report',
      hiring: 'hiring',
    },
  },

  staffRoles: ['1530531573332447324', '1530531568605597718'],
  managementRoles: ['1530531573332447324', '1530531568605597718'],

  colors: {
    primary: 0x75cff5,
    success: 0x57f287,
    error: 0xed4245,
    warn: 0xfee75c,
    info: 0x5865f2,
  },

  departments: {
    general: {
      enabled: true,
      name: 'General Support',
      emoji: '🛟',
      color: 0x75cff5,
      supportRoleId: '1530554415558299709',
      categoryId: '1530532240331771914',
      closedCategoryId: '',
      openingMessage: 'Describe your issue below and our support team will assist you shortly.',
      questions: [
        {
          id: 'issue',
          label: 'What do you need help with?',
          type: 'short',
          required: true,
          minimumLength: 3,
          maximumLength: 200,
          placeholder: 'Describe your issue...',
          page: 1,
          order: 1,
          enabled: true,
        },
        {
          id: 'extra',
          label: 'Any extra details?',
          type: 'paragraph',
          required: false,
          minimumLength: 0,
          maximumLength: 1000,
          placeholder: 'Optional details...',
          page: 1,
          order: 2,
          enabled: true,
        },
      ],
    },

    reports: {
      enabled: true,
      name: 'Reports',
      emoji: '🚨',
      color: 0xed4245,
      supportRoleId: '1530554438945738883',
      categoryId: '1530532184480550923',
      closedCategoryId: '',
      openingMessage: 'Your report is confidential. The reported user will never be automatically added to this ticket.',
      questions: [
        {
          id: 'target',
          label: 'Who are you reporting?',
          type: 'short',
          required: true,
          minimumLength: 2,
          maximumLength: 100,
          placeholder: 'Username or ID...',
          page: 1,
          order: 1,
          enabled: true,
        },
        {
          id: 'reason',
          label: 'Why are you reporting them?',
          type: 'paragraph',
          required: true,
          minimumLength: 10,
          maximumLength: 2000,
          placeholder: 'Describe the issue in detail...',
          page: 1,
          order: 2,
          enabled: true,
        },
        {
          id: 'evidence',
          label: 'Any evidence? (links/screenshots)',
          type: 'paragraph',
          required: false,
          minimumLength: 0,
          maximumLength: 1000,
          placeholder: 'Paste links or describe...',
          page: 1,
          order: 3,
          enabled: true,
        },
      ],
    },

    hiring: {
      enabled: true,
      name: 'Hiring',
      emoji: '💼',
      color: 0x9b59b6,
      supportRoleId: '1530554455018176552',
      categoryId: '1530532279242457128',
      closedCategoryId: '',
      openingMessage: 'Want to hire Caliber? Fill out the details below and we\'ll get back to you.',
      questions: [
        {
          id: 'server_name',
          label: 'What is your server name?',
          type: 'short',
          required: true,
          minimumLength: 2,
          maximumLength: 100,
          placeholder: 'Enter your server name...',
          page: 1,
          order: 1,
          enabled: true,
        },
        {
          id: 'position',
          label: 'What position or rank are you offering?',
          type: 'short',
          required: true,
          minimumLength: 2,
          maximumLength: 100,
          placeholder: 'e.g. Moderator, Admin, Developer...',
          page: 1,
          order: 2,
          enabled: true,
        },
        {
          id: 'member_count',
          label: 'Current member count?',
          type: 'short',
          required: true,
          minimumLength: 1,
          maximumLength: 20,
          placeholder: 'e.g. 5000',
          page: 1,
          order: 3,
          enabled: true,
        },
        {
          id: 'service_type',
          label: 'What service are you requesting?',
          type: 'short',
          required: true,
          minimumLength: 2,
          maximumLength: 100,
          placeholder: 'Discord Staffing, Minecraft Staffing, Discord Setup, Minecraft Setup, Freelance, Other',
          page: 1,
          order: 4,
          enabled: true,
        },
        {
          id: 'description',
          label: 'Describe the work',
          type: 'paragraph',
          required: true,
          minimumLength: 10,
          maximumLength: 2000,
          placeholder: 'What does the job involve?',
          page: 1,
          order: 5,
          enabled: true,
        },
        {
          id: 'responsibilities',
          label: 'Expected responsibilities?',
          type: 'paragraph',
          required: true,
          minimumLength: 5,
          maximumLength: 2000,
          placeholder: 'What will the hired person be doing?',
          page: 2,
          order: 6,
          enabled: true,
        },
        {
          id: 'deadline',
          label: 'Deadline or preferred start date?',
          type: 'short',
          required: true,
          minimumLength: 2,
          maximumLength: 100,
          placeholder: 'e.g. ASAP, January 1st, Flexible...',
          page: 2,
          order: 7,
          enabled: true,
        },
        {
          id: 'paid_status',
          label: 'Is this paid or unpaid?',
          type: 'short',
          required: true,
          minimumLength: 2,
          maximumLength: 50,
          placeholder: 'Paid, Unpaid, Negotiable, Not sure yet',
          page: 2,
          order: 8,
          enabled: true,
        },
        {
          id: 'additional_info',
          label: 'Any additional information?',
          type: 'paragraph',
          required: false,
          minimumLength: 0,
          maximumLength: 2000,
          placeholder: 'Anything else you want us to know...',
          page: 2,
          order: 9,
          enabled: true,
        },
      ],
    },
  },
};
